Richard/bug fixes
JoshLuong/Trippo pull request #61
Opened 2021-08-10 20:34 UTC by rho1207

2021-08-10 22:25 UTC, josh-luong commented on trippo/src/app/destinations/destinationTypes.tsx
> +  color: ${(props) => props.color};
If you take a look at my PR, you need to actually pass props like this for styled components, or you will get warnings:
` props.$edit ? c.YELLOW : "rgba(0, 0, 0, 0.12)"};`

2021-08-10 22:25 UTC, josh-luong commented on trippo/src/components/itineraryForm/ItineraryOptionsContainer.tsx
> +const tagsData: any[] = [];
if this is just empty, why not remove it?

2021-08-11 19:11 UTC, r-bassi commented on trippo/src/components/itineraryEdit/Day.tsx
>            )}
Doesn't compile for me? add :null after ")" maybe

2021-08-11 19:11 UTC, josh-luong commented on trippo/src/app/destinations/destinationTypes.tsx
> +  color: ${(props) => props.color};
has this been addressed?

2021-08-11 19:11 UTC, josh-luong commented on trippo/src/components/itineraryEdit/Day.styles.ts
> +  edit?: boolean;
has this area been tested? This reversion will break/ causes warning/error on line 21

2021-08-11 19:11 UTC, josh-luong commented on trippo/src/components/itineraryForm/ItineraryOptionsContainer.tsx
> +const tagsData: any[] = [];
is  this being addressed?

2021-08-11 19:15 UTC, r-bassi commented on trippo/src/components/itineraryEdit/Day.styles.ts
>    color: ${c.BLACK};
line 22: props.$edit ? c.YELLOW : "rgba(0, 0, 0, 0.12)"};

edit is not recognized, remove $ since now edit={edit} in Day.tsx?

2021-08-11 19:44 UTC, rho1207 commented on trippo/src/components/itineraryForm/ItineraryOptionsContainer.tsx
> +const tagsData: any[] = [];
its a required field for autocomplete, cant get rid of it.

2021-08-11 21:57 UTC, andreram requested changes, later dismissed
Branch currently doesn't compile. Also what bugs were fixed? Idk what to test

2021-08-11 21:57 UTC, andreram commented on trippo/src/components/itineraryEdit/Day.tsx
> +          <sc.StickyDiv>
what's up with this indent?

2021-08-11 21:57 UTC, andreram commented on trippo/src/components/itineraryForm/ItineraryOptionsContainer.tsx
> +const tagsData: any[] = [];
can you make the prop `options={tagsData}`?

2021-08-11 21:57 UTC, andreram commented on trippo/src/components/itineraryForm/MainEditItineraryContainer.tsx
> +                setErrorMessage("Something went wrong. Make sure itinerary names are unique or try again later.")
Ideally the error message should come from the backend. If the request fails because of the names we'd send back a specific error message for that, otherwise we'd send something generic

2021-08-11 21:57 UTC, andreram commented on trippo/src/components/itineraryForm/MainEditItineraryContainer.tsx
> +                        defaultMaxTravel={maxTravel} setMaxTravel={setMaxTravel} />
Can you put these props on separate lines?

2021-08-11 21:57 UTC, andreram commented on trippo/src/components/itineraryForm/NewItineraryContainer.tsx
> +                        defaultMaxTravel={maxTravel} setMaxTravel={setMaxTravel} />
Likewise with separate lines, I think it'd look cleaner

2021-08-11 21:57 UTC, andreram commented on trippo/src/app/destinations/destinationTypes.tsx
> +  color: ${(props) => props.color};
to add on -- you can define types for your props by passing in generics like this:
`const ShoppingIcon = styled.i<{ color: string }>`

2021-08-11 21:57 UTC, andreram commented on trippo/src/components/itineraryEdit/Day.tsx
> +          {!isReadOnly && dayActivities.length > 0 ? (
like @r-bassi said, this doesn't compile. replace the `? (` with `&& (`

2021-08-11 21:57 UTC, andreram commented on trippo/src/components/itineraryEdit/Day.styles.ts
>    color: ${c.BLACK};
the $ here isn't related, this is just for string interpolation

2021-08-12 00:01 UTC, andreram reviewed
Code looks good, still don't know what to test so not sure about giving an approval. You can go ahead and merge if you're confident with the changes I guess

2021-08-12 00:01 UTC, andreram commented on trippo/src/components/aboutPage/AboutPage.styles.ts
>  export const StyledEmailIcon = styled(EmailIcon)``;
Can we remove this?

2021-08-12 00:01 UTC, andreram commented on trippo/src/components/itineraryForm/ItineraryOptionsContainer.tsx
> +const tagsData: any[] = [];
edited previous comment because I didn't change the pasted line lol

2021-08-12 03:33 UTC, JoshLuong approved these changes
🙏

2021-08-12 03:34 UTC, merged